server:
  host: "localhost"
  port: "10111"

postgres:
  dsn:

redis:
  addr:
  password:
  db: 0

elasticsearch:
  addr:

log:
  logfile: "./log", # 日志文件路径
  maxsize: 10,  # 日志文件最大大小，单位M
  max_age: 30,  # 日志保留天数
  compress: false, # 日志压缩
  localtime: true # 使用本地时间

jwt:
  secret: ""
  expire: 3600 # 过期时间，单位秒

email:
  smtp_user:
  smtp_password:
  smtp_nickname:
  smtp_host: "smtp.qq.com"
  smtp_port: "587"

captcha:
  length: 6 # 验证码长度
  timeout: 300 # 验证码过期时间
  interval: 60 # 验证码发送间隔

user:
  admin:
    email: "default@EMAIL" # 初始超级管理员登录邮箱
    password: "123456" # 初始超级管理员账户密码
  nickname:
    rand_min: 8 # 无昵称用户随机昵称最小长度
    rand_max: 16 # 无昵称用户随机昵称最大长度
    max_length: 20 # 昵称最大长度