server:
  host: "localhost"
  port: "8080"
  env: "dev"

postgres:
  dsn: ""

user:
  initAdmin:
    email: "admin@example.com"
    password: "securepassword"

smtp:
  smtpUser: ""
  smtpNickname: ""
  smtpPassword: ""
  smtpHost: "smtp.qq.com"
  smtpPort: "587"
  captcha:
    expire: "15m"
    interval: "1m"
  weeklyEmail:
    routineNum: 10
    timeOut: "10s"
    rateLimit: "1m"

jwt:
  secret: "your_jwt_secret"
  expiration: "24h"

log:
  logfile: "./appLog.log"
  maxsize: 10
  maxAge: 30
  compress: false
  localTime: true

redis:
  addr: ""
  password: ""
  db: 0

bcrypt:
  cost: 10